Blogging/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include("django.contrib.auth.urls")),
    path("signup/",include("signup.urls")),
    path(r'captcha/', include('captcha.urls')),
    path("",include("blogs.urls")),

]

blogs/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import PicCreateview,Articles_View,ArticlesView2,HomeView,After_Adding_View
from .views import stream_file
from django.views.generic import TemplateView

app_name="blogs"

urlpatterns = [
    path("home/",HomeView.as_view(),name="homepage"),
    path("blogs/",PicCreateview.as_view(),name="create_pic"),
    path("blogs/list/<int:pk>",Articles_View.as_view(),name="list_articles"),
    path('pic_picture/<int:pk>', stream_file, name='pic_picture'),
    path('pic_list',ArticlesView2.as_view(),name="list_article"),
    path('',After_Adding_View.as_view(),name="after")

]

signup/urls.py
from django.conf.urls import url
from .views import UserForm
from django.urls import path,include
app_name="signup"
urlpatterns=[
    path("",UserForm.as_view(),name="signup")
]

blogs/models.py
from django.db import models
from django.conf import settings

# Create your models here.



class Blog(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    title = models.CharField(max_length=200)

    description = models.TextField()

    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True,
                                    help_text='The MIMEType of the file')



    public = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import Blog
from django.core.files.uploadedfile import InMemoryUploadedFile
from .humanize import naturalsize
#from math_captcha import MathCaptchaModelForm


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Blog
        fields = ['title','description', 'picture', 'public']  # Picture

    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < " + self.max_upload_limit_text + " bytes")

    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

signup/forms.py
from django import forms
from captcha.fields import CaptchaField

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from simplemathcaptcha.fields import MathCaptchaField



class NewUserForm(UserCreationForm):

    captcha = MathCaptchaField()

    class Meta:
        model=User
        fields = ("username", "password1", "password2")

blogs/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import CreateForm
from django.urls import reverse_lazy,reverse
from .models import Blog
from django.conf import settings
from django.contrib.auth.models import User
# Create your views here.




class PicCreateview(LoginRequiredMixin,View):
    template_name = 'blogs/form.html'
    success_url = reverse_lazy('pics:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()
        return redirect(reverse("blogs:after"))



class Articles_View(LoginRequiredMixin,View):

    def get(self,request,pk):
        objects=Blog.objects.filter(owner=pk)

        ctx ={"objects":objects}
        return render(request,"blogs/done.html",ctx)


class Searched_Articles_View(LoginRequiredMixin,View):

    def get(self,request,pk):
        objects=Blog.objects.filter(owner=pk,public=True)

        ctx ={"objects":objects}
        return render(request,"blogs/done.html",ctx)



def stream_file(request, pk):
    pic = get_object_or_404(Blog, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response


class ArticlesView2(View,LoginRequiredMixin):

    def get(self, request):
        username = request.GET.get("searched")
        objects1 = User.objects.filter(username=username)
        objects=None
        try:
            objects = Blog.objects.filter(owner=objects1[0].id,public=True)
        except:
            objects=None

        ctx = {"objects": objects}
        return render(request, "blogs/done.html", ctx)


class HomeView(View):

    def get(self,request):

        return render(request,"blogs/home.html")



class After_Adding_View(View,LoginRequiredMixin):

    def get(self,request):
        user = request.user.id

        objects = Blog.objects.filter(owner=user)
        return render(request,"blogs/list.html",{"objects":objects})

home/views.py
from django.shortcuts import render

# Create your views here.

signup/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import NewUserForm
from django.views import View
from django.urls import reverse_lazy


# Create your views here.





class UserForm(View):

    def get(self,request):
        form = NewUserForm()
        ctx = {"form":form}
        return render(request,"signup/signup.html",ctx)


    def post(self,request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username,password=raw_password)
            login(request,user)
            return redirect(reverse_lazy("blogs:after"))
        else:
            ctx={"form":form}
            return render(request,"signup/signup.html",ctx)

blogs/templates/blogs/done.html
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% if objects %}
{% for object in objects %}
<p>
{{object.title}}

<br> <br>

{{object.description}}<br><br>
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'blogs:pic_picture' object.id %}">
<br><br></p>
<hr size="8" width="100%" color="black">
{% endfor %}
{% else %}

No articles till now <br><br>

{% endif %}

{% if user.is_authenticated %}
<a href="{% url 'blogs:create_pic' %}">Create Your New Article</a> |
<a href="{% url 'logout' %}">Logout</a>
{% else %}
{% endif %}
<br><br>
<a href="{% url 'blogs:homepage' %}"> Go to Search Page</a>
<br><br><br>

blogs/templates/blogs/form.html
{% load crispy_forms_tags %}

<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'blogs:after' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>

blogs/templates/blogs/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


{% if user.is_authenticated %}
<h2> Search for articles by username</h2>

<form method="GET" action="{% url 'blogs:list_article' %}">

    <input type="text" name="searched">
    <input type="submit" value="submit">
</form>
<a href="{% url 'blogs:list_articles' user.id %}">See your articles</a>
{% else %}
<a href="{% url 'login' %}">Login to search articles</a>
{% endif %}
<br>


</body>
</html>

blogs/templates/blogs/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Welcome Page</h1>

<br><br>

{% if user.is_authenticated %}

{% if objects %}

{% for object in objects %}
<h2>{{object.title}}</h2>
<br> <br>
{{object.description}}<br><br>
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'blogs:pic_picture' object.id %}">
<br><br>
<hr size="8" width="100%" color="black">



{% endfor %}

{% else %}

No Article Till Now , Create a New Article
<br><br>

{% endif %}



<a href="{% url 'blogs:create_pic' %}">Create Article</a> |
<a href="{% url 'logout' %}">Logout</a> <br><br>
<a href="{% url 'blogs:homepage'%}">Go to search page</a>
{% else %}

<a href="{% url 'login' %}">Login to create articles or seach for articles</a> |
<a href="{% url 'signup:signup'%}">Register if a new user</a>


{% endif %}
<br><br>

<br><br><br>
</body>
</html>

blogs/templates/blogs/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

operation done


</body>
</html>

signup/templates/signup/signup.html
{% load crispy_forms_tags %}


<form method="post" action="">
    {% csrf_token %}

    {{form|crispy}}

    <input type="submit" class="btn btn-success" value="Signup">
    <input type="submit" value="Cancel" onclick="window.location='{% url 'login' %}' ; return false;" class="btn btn-primary">
</form>